version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: nai_user
      POSTGRES_PASSWORD: nai_password
      POSTGRES_DB: nai_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cloudberry-storage:
    build:
      context: ./cloudberry-storage
    depends_on:
      - postgres

  front:
     build:
       context: ./nai-frontend
     # restart: always
     depends_on:
       - prompt-service
     ports:
       - "5173:5173"

  prompt-service:
    build:
      context: ./prompt-service
    environment:
      CLOUDBERRY_HOST: 176.123.160.174
      CLOUDBERRY_PORT: 8002
      DB_URL: jdbc:postgresql://postgres:5432/nai_db
      DB_USER: nai_user
      DB_PASSWORD: nai_password
    depends_on:
      - postgres
      - cloudberry-storage
    ports:
      - "8080:8080"
    volumes:
      - ./buckets.json:/app/buckets.json

  envoy:
    image: envoyproxy/envoy:v1.27.0  # Указываем версию Envoy
    ports:
      - "9901:9901"    # Порт для админ-панели Envoy
      - "8081:8081"    # Порт для клиента (React)
    depends_on:
      - prompt-service
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml  # Подключаем конфигурационный файл

volumes:
  postgres_data:
