version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: nai_user
      POSTGRES_PASSWORD: nai_password
      POSTGRES_DB: nai_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql

volumes:
  postgres_data: